// Pure-function code generators for `think crud`. Each function takes a
// TableInfo and returns the file contents as a string. Output mirrors the
// Category controller pattern that's already test-verified.
import type { TableInfo, ColumnInfo } from './schema-introspect.ts'

/** Convert snake_case / fa_snake_case to PascalCase. */
export function pascalCase(s: string): string {
  return s.replace(/^fa_/, '').replace(/(?:^|_)(\w)/g, (_, c) => (c as string).toUpperCase())
}

/** Convert snake_case to camelCase, drop fa_ prefix. */
export function shortName(s: string): string {
  return s.replace(/^fa_/, '')
}

/**
 * FastAdmin's framework / core tables — `php think crud` must NOT scaffold
 * these (their controllers are hand-written and security-sensitive, and a
 * generated controller would collide with the existing one). Mirrors the
 * doc's explicit warning against running CRUD on core tables.
 */
const PROTECTED_TABLES = new Set([
  'admin', 'admin_log', 'auth_group', 'auth_group_access', 'auth_rule',
  'config', 'attachment', 'user', 'user_group', 'user_rule', 'user_token',
  'user_money_log', 'user_score_log', 'ems', 'sms', 'area', 'category', 'token',
])

/** True when `table` is a framework/core table CRUD generation must refuse. */
export function isProtectedTable(table: string): boolean {
  return PROTECTED_TABLES.has(String(table).toLowerCase().replace(/^fa_/, ''))
}

function tsTypeForColumn(c: ColumnInfo): string {
  if (c.dataType === 'tinyint' && c.columnType === 'tinyint(1)') return 'boolean'
  if (['int', 'bigint', 'smallint', 'mediumint', 'tinyint', 'decimal', 'float', 'double'].includes(c.dataType)) return 'number'
  if (c.enumValues) return 'string'
  return 'string'
}

// TypeORM only accepts `length` on string-family columns. enum / set / text /
// numeric types throw "Column X does not support length property" if it's
// present. `set` is mapped to `varchar` below so it keeps its length.
const LENGTH_SUPPORTED = new Set(['varchar', 'char', 'set', 'varbinary', 'binary'])

function typeormTypeForColumn(c: ColumnInfo): { type: string; extra: string } {
  const opts: string[] = []
  if (c.unsigned) opts.push('unsigned: true')
  if (c.length && LENGTH_SUPPORTED.has(c.dataType)) opts.push(`length: ${c.length}`)
  if (c.nullable) opts.push('nullable: true')
  if (c.default !== null && c.default !== undefined && c.default !== '') {
    opts.push(`default: ${JSON.stringify(c.default)}`)
  } else if (c.default === '') {
    opts.push(`default: ''`)
  }
  if (c.comment) opts.push(`comment: ${JSON.stringify(c.comment)}`)

  const extra = opts.length > 0 ? ', ' + opts.join(', ') : ''

  // Direct MySQL→TypeORM type map; bigints come through as strings from mysql2
  // so we add a transformer.
  if (c.dataType === 'bigint') {
    return {
      type: 'bigint',
      extra: `, transformer: { from: (v: string | null) => v == null ? null : Number(v), to: (v: number | null) => v }${extra}`,
    }
  }
  if (c.dataType === 'enum' && c.enumValues) {
    return { type: 'enum', extra: `, enum: ${JSON.stringify(c.enumValues)}${extra}` }
  }
  if (c.dataType === 'set') {
    // Set columns store as comma-joined string at the wire level; keep as varchar.
    return { type: 'varchar', extra }
  }
  return { type: c.dataType, extra }
}

export function generateEntity(table: TableInfo): string {
  const Class = pascalCase(table.name) + 'Entity'
  const lines: string[] = []
  lines.push(`// Auto-generated by \`bin/think crud -t ${table.name}\`. Edit freely.`)
  lines.push(`import { Column, Entity, PrimaryGeneratedColumn, PrimaryColumn } from 'typeorm'`)
  lines.push('')
  lines.push(`@Entity({ name: '${table.name}' })`)
  lines.push(`export class ${Class} {`)
  for (const col of table.columns) {
    const tsT = tsTypeForColumn(col)
    if (col.isPk && col.isAuto) {
      lines.push(`  @PrimaryGeneratedColumn({ type: '${col.dataType}' })`)
      lines.push(`  ${col.name}!: ${tsT}`)
    } else if (col.isPk) {
      const { type, extra } = typeormTypeForColumn(col)
      lines.push(`  @PrimaryColumn({ type: '${type}'${extra} })`)
      lines.push(`  ${col.name}!: ${tsT}`)
    } else {
      const { type, extra } = typeormTypeForColumn(col)
      const nullableTs = col.nullable ? ' | null' : ''
      lines.push(`  @Column({ type: '${type}'${extra} })`)
      lines.push(`  ${col.name}!: ${tsT}${nullableTs}`)
    }
    lines.push('')
  }
  lines.push(`}`)
  return lines.join('\n')
}

/**
 * Build the bootstrap-table `columns` literal for the list page. A CRUD-
 * generated controller has no hand-written `public/assets/js/backend/<x>.js`,
 * so the table is initialised inline (`useInlineInit: true`) and needs the
 * column set spelled out. Heavy columns (text / long varchar) are skipped to
 * keep the grid readable; an `operate` column is always appended.
 */
function buildColumnsLiteral(table: TableInfo): string {
  const cols: string[] = ['{ checkbox: true }']
  let shown = 0
  for (const c of table.columns) {
    if (shown >= 10) break
    if (c.dataType === 'text') continue
    if (c.dataType === 'varchar' && (c.length ?? 0) > 500) continue
    const title = pascalCase(c.name).replace(/([A-Z])/g, ' $1').trim()
    if (c.isPk) {
      cols.push(`{ field: '${c.name}', title: '${title}', sortable: true }`)
    } else {
      cols.push(`{ field: '${c.name}', title: '${title}' }`)
    }
    shown++
  }
  cols.push(`{ operate: true, title: 'Operate' }`)
  return '[\n        ' + cols.join(',\n        ') + ',\n      ]'
}

/**
 * Columns literal for the Recycle Bin grid. Like `buildColumnsLiteral` but
 * trimmed to ~6 data columns and always followed by a `deletetime` column
 * (datetime-formatted) so the operator can see when each row was binned. The
 * `operate` column is rebound to Restore / Destroy buttons by
 * `renderRecyclebinInitScript`.
 */
function buildRecyclebinColumnsLiteral(table: TableInfo): string {
  const cols: string[] = ['{ checkbox: true }']
  let shown = 0
  for (const c of table.columns) {
    if (shown >= 6) break
    if (c.dataType === 'text') continue
    if (c.dataType === 'varchar' && (c.length ?? 0) > 500) continue
    if (['createtime', 'updatetime', 'deletetime'].includes(c.name)) continue
    const title = pascalCase(c.name).replace(/([A-Z])/g, ' $1').trim()
    if (c.isPk) {
      cols.push(`{ field: '${c.name}', title: '${title}', sortable: true }`)
    } else {
      cols.push(`{ field: '${c.name}', title: '${title}' }`)
    }
    shown++
  }
  cols.push(`{ field: 'deletetime', title: 'Delete Time', formatter: 'Table.api.formatter.datetime' }`)
  cols.push(`{ operate: true, title: 'Operate' }`)
  return '[\n        ' + cols.join(',\n        ') + ',\n      ]'
}

export function generateController(table: TableInfo): string {
  const slug = shortName(table.name)
  const Class = pascalCase(table.name)
  const EntityClass = Class + 'Entity'
  const columnsLiteral = buildColumnsLiteral(table)
  // Recycle-bin support is emitted only when the table has a `deletetime`
  // column (PHP's SoftDelete trait equivalent) — otherwise del() hard-deletes
  // and there is nothing to recover.
  const hasSoftDelete = table.columns.some((c) => c.name === 'deletetime')
  const recyclebinColumnsLiteral = buildRecyclebinColumnsLiteral(table)
  const searchFields = table.columns
    .filter((c) => ['varchar', 'char', 'text'].includes(c.dataType) && !c.isPk)
    .slice(0, 3)
    .map((c) => c.name)
    .join(',') || 'id'

  return `// Auto-generated by \`bin/think crud -t ${table.name}\`. Edit freely.
import { All, Body, Controller, Get, HttpCode, Param, Post, Query, Req, UseGuards } from '@nestjs/common'
import { InjectRepository } from '@nestjs/typeorm'
import { Repository } from 'typeorm'
import type { Request } from 'express'
import { ${EntityClass} } from '../../entities/${slug}.entity.ts'
import { adminErr, adminOk, type AdminEnvelope } from '../../common/envelope.ts'
import { AdminAuthGuard } from '../../guards/admin-auth.guard.ts'
import { CsrfService, type SessionWithToken } from '../../services/csrf.service.ts'
import { BackendCrudService, parseStr } from '../../services/backend-crud.service.ts'
import { ViewService } from '../../services/view.service.ts'
import { NoNeedRight } from '../../common/no-need-right.decorator.ts'

interface ${Class}Session extends SessionWithToken {
  admin?: { id: number; username: string } | undefined
}
type ${Class}Req = Request & { session: ${Class}Session & { [k: string]: unknown } }

@Controller('admin.php/${slug}')
@UseGuards(AdminAuthGuard)
@NoNeedRight(['selectpage'])
export class ${Class}Controller {
  private readonly crud: BackendCrudService<${EntityClass}>

  constructor(
    @InjectRepository(${EntityClass}) private readonly repo: Repository<${EntityClass}>,
    private readonly csrf: CsrfService,
    private readonly view: ViewService,
  ) {
    this.crud = new BackendCrudService(this.repo, {
      searchFields: '${searchFields}',
      multiFields: 'status',
    })
  }

  @Get('index')
  async indexGet(@Req() req: ${Class}Req, @Query() q: Record<string, string>): Promise<unknown> {
    if (!isAjax(req)) {
      return this.view.renderListPage({
        pageTitle: '${pascalCase(table.name)}',
        tableId: 'table',
        indexUrl: '/admin.php/${slug}/index',
        addUrl: '/admin.php/${slug}/add',
        editUrl: '/admin.php/${slug}/edit',
        delUrl: '/admin.php/${slug}/del',
        multiUrl: '/admin.php/${slug}/multi',
        importUrl: '/admin.php/${slug}/import',${hasSoftDelete ? `
        recyclebinUrl: '/admin.php/${slug}/recyclebin',` : ''}
        // A CRUD-generated controller has no PHP-asset backend JS file, so the
        // bootstrap-table is initialised inline; columns must be supplied.
        useInlineInit: true,
        columns: ${columnsLiteral},
        req,
        controllername: '${slug}',
        actionname: 'index',
      })
    }
    return this.crud.index(q as Record<string, unknown>)
  }

  @Post('index')
  @HttpCode(200)
  async indexPost(@Query() q: Record<string, string>): Promise<{ total: number; rows: ${EntityClass}[] }> {
    return this.crud.index(q as Record<string, unknown>)
  }

  @Get('add')
  getAdd(@Req() req: ${Class}Req): string {
    const tok = this.csrf.issue(req.session)
    return this.view.renderFormPage({
      pageTitle: '${pascalCase(table.name)} - Add',
      formId: 'add-form',
      formAction: '/admin.php/${slug}/add',
      __token__: tok,
      fields: ${renderFieldsLiteral(table)},
      req,
      controllername: '${slug}',
      actionname: 'add',
    })
  }

  @Post('add')
  @HttpCode(200)
  async postAdd(@Req() req: ${Class}Req, @Body() body: Record<string, unknown>): Promise<AdminEnvelope<unknown>> {
    if (!this.csrf.consume(req.session, String(body['__token__'] ?? ''))) {
      return adminErr('Token verification error', { __token__: this.csrf.issue(req.session) })
    }
    const row = body['row']
    if (!row || typeof row !== 'object') return adminErr('Parameter %s can not be empty')
    const r = await this.crud.add(row as Record<string, unknown>)
    if (!r.ok) return adminErr(r.error ?? 'No rows were inserted')
    return adminOk('', { id: r.id })
  }

  @Get('edit/ids/:id')
  async getEdit(@Req() req: ${Class}Req, @Param('id') idStr: string): Promise<unknown> {
    const id = parseInt(idStr, 10)
    const row = await this.repo.findOneBy({ id } as any)
    if (!row) return adminErr('No Results were found')
    const tok = this.csrf.issue(req.session)
    return this.view.renderFormPage({
      pageTitle: '${pascalCase(table.name)} - Edit',
      formId: 'edit-form',
      formAction: '/admin.php/${slug}/edit',
      __token__: tok,
      idsField: \`<input type="hidden" name="ids" value="\${id}">\`,
      fields: ${renderFieldsLiteral(table)},
      req,
      controllername: '${slug}',
      actionname: 'edit',
    })
  }

  @Post('edit')
  @HttpCode(200)
  async postEdit(@Req() req: ${Class}Req, @Body() body: Record<string, unknown>): Promise<AdminEnvelope<unknown>> {
    if (!this.csrf.consume(req.session, String(body['__token__'] ?? ''))) {
      return adminErr('Token verification error', { __token__: this.csrf.issue(req.session) })
    }
    const id = parseInt(String(body['ids'] ?? '0'), 10)
    if (!Number.isFinite(id) || id <= 0) return adminErr('No Results were found')
    const row = body['row']
    if (!row || typeof row !== 'object') return adminErr('Parameter %s can not be empty')
    const r = await this.crud.edit(id, row as Record<string, unknown>)
    if (!r.ok) return adminErr(r.error ?? 'No rows were updated')
    return adminOk('')
  }

  @Post('del')
  @HttpCode(200)
  async del(@Body() body: Record<string, unknown>): Promise<AdminEnvelope<unknown>> {
    const ids = String(body['ids'] ?? '').trim()
    if (!ids) return adminErr('Parameter %s can not be empty')
    const count = await this.crud.del(ids)
    if (!count) return adminErr('No rows were deleted')
    return adminOk('')
  }

  @Post('multi')
  @HttpCode(200)
  async multi(@Body() body: Record<string, unknown>): Promise<AdminEnvelope<unknown>> {
    const ids = String(body['ids'] ?? '').trim()
    if (!ids) return adminErr('Parameter %s can not be empty')
    const paramsStr = String(body['params'] ?? '')
    if (!paramsStr) return adminErr('No rows were updated')
    const values = parseStr(paramsStr)
    const count = await this.crud.multi(ids, values, true)
    if (!count) return adminErr('No rows were updated')
    return adminOk('')
  }

  // CSV import — \`.btn-import\` uploads a .csv then POSTs {file: <url>} here.
  // The first CSV row is a header line matched against column comments/names.
  @Post('import')
  @HttpCode(200)
  async importRows(@Body() body: Record<string, unknown>): Promise<AdminEnvelope<unknown>> {
    const file = String(body?.['file'] ?? '').trim()
    if (!file) return adminErr('Parameter %s can not be empty')
    const r = await this.crud.import(file)
    if (!r.ok) return adminErr(r.error ?? 'No rows were updated')
    return adminOk('')
  }

  // The fastadmin-selectpage plugin POSTs its queries (doc 178); accept both.
  @All('selectpage')
  selectpage(@Query() q: Record<string, unknown>, @Body() body: Record<string, unknown>): Promise<{ list: Array<Record<string, unknown>>; total: number }> {
    return this.crud.selectpage({ ...(body ?? {}), ...q } as any)
  }
${hasSoftDelete ? `
  // -------- Recycle Bin (SoftDelete trait parity) --------
  // del() above only sets \`deletetime\`; these actions list / restore / purge
  // the binned rows. Mirrors PHP Backend::recyclebin()/restore()/destroy().
  @Get('recyclebin')
  async recyclebinGet(@Req() req: ${Class}Req, @Query() q: Record<string, string>): Promise<unknown> {
    if (!isAjax(req)) {
      return this.view.renderRecyclebinPage({
        pageTitle: '${pascalCase(table.name)} - Recycle Bin',
        tableId: 'table',
        recyclebinUrl: '/admin.php/${slug}/recyclebin',
        restoreUrl: '/admin.php/${slug}/restore',
        destroyUrl: '/admin.php/${slug}/destroy',
        columns: ${recyclebinColumnsLiteral},
        req,
        controllername: '${slug}',
        actionname: 'recyclebin',
      })
    }
    return this.crud.recyclebin(q as Record<string, unknown>)
  }

  @Post('recyclebin')
  @HttpCode(200)
  async recyclebinPost(@Query() q: Record<string, string>): Promise<{ total: number; rows: ${EntityClass}[] }> {
    return this.crud.recyclebin(q as Record<string, unknown>)
  }

  // Empty \`ids\` restores / destroys the whole bin — that's what the
  // \`.btn-restoreall\` / \`.btn-destroyall\` toolbar buttons POST (no ids).
  @Post('restore')
  @HttpCode(200)
  async restore(@Body() body: Record<string, unknown>, @Query() q: Record<string, string>): Promise<AdminEnvelope<unknown>> {
    // \`@Body()\` is \`undefined\` for a POST with no body — that is exactly what
    // the no-id \`.btn-restoreall\` / \`.btn-destroyall\` toolbar buttons send, so
    // both accessors must be optional-chained.
    const ids = String(body?.['ids'] ?? q?.['ids'] ?? '').trim()
    const count = await this.crud.restore(ids)
    if (!count) return adminErr('No rows were updated')
    return adminOk('')
  }

  @Post('destroy')
  @HttpCode(200)
  async destroy(@Body() body: Record<string, unknown>, @Query() q: Record<string, string>): Promise<AdminEnvelope<unknown>> {
    // \`@Body()\` is \`undefined\` for a POST with no body — that is exactly what
    // the no-id \`.btn-restoreall\` / \`.btn-destroyall\` toolbar buttons send, so
    // both accessors must be optional-chained.
    const ids = String(body?.['ids'] ?? q?.['ids'] ?? '').trim()
    const count = await this.crud.destroy(ids)
    if (!count) return adminErr('No rows were updated')
    return adminOk('')
  }
` : ''}}

function isAjax(req: Request): boolean {
  return String(req.headers['x-requested-with'] ?? '').toLowerCase() === 'xmlhttprequest'
}
`
}

/**
 * Generate the controller's browser-side AMD module
 * (`public/assets/js/backend/<slug>.js`). PHP's `php think crud` emits this
 * file too — `require-backend.js` auto-loads `Config.jsname` (= `backend/<slug>`)
 * and 404s noisily without it.
 *
 * The list page is initialised inline by the server template
 * (`useInlineInit`), so `Controller.index()` is a no-op. The add / edit forms
 * rely on this module's `Form.api.bindevent` to wire AJAX submit + dialog
 * close.
 */
export function generateBackendJs(table: TableInfo): string {
  const slug = shortName(table.name)
  return `// Auto-generated by \`bin/think crud -t ${table.name}\`. Edit freely.
define(['jquery', 'bootstrap', 'backend', 'table', 'form'], function ($, undefined, Backend, Table, Form) {
    var Controller = {
        index: function () {
            // The list table is initialised inline by the server-rendered
            // template (renderListPage useInlineInit). Nothing to do here.
        },
        recyclebin: function () {
            // The recycle-bin table is initialised inline by the server-
            // rendered template (renderRecyclebinPage). Nothing to do here.
        },
        add: function () {
            Form.api.bindevent($("form[role=form]"));
        },
        edit: function () {
            Form.api.bindevent($("form[role=form]"));
        },
        api: {
            bindevent: function () {
                Form.api.bindevent($("form[role=form]"));
            }
        }
    };
    return Controller;
});
`
}

function renderFieldsLiteral(table: TableInfo): string {
  // Generate a JS template literal that produces the <input> markup for each
  // non-pk, non-timestamp column. The widget chosen for each column follows
  // the FastAdmin field→component rules documented in database.html +
  // docs 177-186, 736 (upload / SelectPage / validator / city / datetime /
  // switch / slider / tagsinput / daterange):
  //   - category_id(s) / user_id(s) / admin_id(s) → SelectPage   (doc 178)
  //   - `city`                                     → city-picker (doc 180)
  //   - date / datetime / timestamp / *time        → datetimepicker (doc 181)
  //   - *range                                     → datetimerange (doc 736)
  //   - `switch` / tinyint(1)                       → switcher    (doc 185)
  //   - `tags` / *tags                              → tagsinput   (doc 1207)
  //   - image / images / *image(s)                  → faupload    (doc 177/183)
  //   - enum                                       → <select>
  //   - set                                        → <select multiple>
  //   - text                                       → <textarea>
  //   - NOT NULL columns                           → data-rule="required"
  const inputs: string[] = []
  for (const c of table.columns) {
    if (c.isPk) continue
    if (['createtime', 'updatetime', 'deletetime'].includes(c.name)) continue
    const label = c.comment || c.name
    const required = !c.nullable && (c.default === null || c.default === undefined)
    const ruleAttr = required ? ' data-rule="required"' : ''
    const wrap = (inner: string): string =>
      `'<div class="form-group"><label class="col-xs-2 control-label">${escapeForTemplate(label)}</label><div class="col-xs-8">${escapeForTemplate(inner)}</div></div>'`

    // SelectPage — relation id columns (doc 178).
    if (/^(category|user|admin)_ids?$/.test(c.name)) {
      const rel = c.name.startsWith('category') ? 'category' : c.name.startsWith('user') ? 'user/user' : 'auth/admin'
      const multi = c.name.endsWith('_ids') ? ' data-multiple="true"' : ''
      inputs.push(wrap(`<input class="form-control selectpage" data-source="${rel}/selectpage"${multi}${ruleAttr} name="row[${c.name}]" type="text" value="">`))
    // city-picker (doc 180).
    } else if (c.name === 'city' || /city$/.test(c.name)) {
      inputs.push(wrap(`<input class="form-control" data-toggle="city-picker"${ruleAttr} name="row[${c.name}]" type="text" value="">`))
    // datetimerange — *range columns (doc 736). Checked before datetimepicker.
    } else if (/range$/.test(c.name)) {
      inputs.push(wrap(`<input class="form-control datetimerange"${ruleAttr} name="row[${c.name}]" type="text" value="">`))
    // datetimepicker — date/datetime/timestamp columns or *time suffix (doc 181).
    } else if (['date', 'datetime', 'timestamp'].includes(c.dataType) || /time$/.test(c.name)) {
      const fmt = c.dataType === 'date' ? 'YYYY-MM-DD' : 'YYYY-MM-DD HH:mm:ss'
      inputs.push(wrap(`<input class="form-control datetimepicker" data-date-format="${fmt}"${ruleAttr} name="row[${c.name}]" type="text" value="">`))
    // switcher — `switch` column or tinyint(1) (doc 185).
    } else if (c.name === 'switch' || c.dataType === 'tinyint') {
      inputs.push(wrap(`<input id="c-${c.name}" name="row[${c.name}]" type="hidden" value="1"><a href="javascript:;" data-toggle="switcher" class="btn-switcher" data-input-id="c-${c.name}" data-yes="1" data-no="0"><i class="fa fa-toggle-on text-success fa-2x"></i></a>`))
    // tagsinput — `tags` column or *tags suffix (doc 1207).
    } else if (c.name === 'tags' || /tags$/.test(c.name)) {
      inputs.push(wrap(`<input class="form-control" data-role="tagsinput"${ruleAttr} name="row[${c.name}]" type="text" value="">`))
    // faupload — image / file columns (doc 177 / 183).
    } else if (/images?$/.test(c.name) || /file$/.test(c.name)) {
      const isMulti = /images$/.test(c.name)
      const mime = /images?$/.test(c.name) ? 'image/*' : '*'
      inputs.push(wrap(
        `<div class="input-group">` +
        `<input id="c-${c.name}" class="form-control"${ruleAttr} name="row[${c.name}]" type="text" value="">` +
        `<div class="input-group-addon no-border no-padding">` +
        `<span><button type="button" class="btn btn-danger faupload" data-input-id="c-${c.name}" data-mimetype="${mime}" data-multiple="${isMulti}"><i class="fa fa-upload"></i> 上传</button></span> ` +
        `<span><button type="button" class="btn btn-primary fachoose" data-input-id="c-${c.name}" data-mimetype="${mime}" data-multiple="${isMulti}"><i class="fa fa-list"></i> 选择</button></span>` +
        `</div></div>`,
      ))
    // fieldlist — dynamic key/value list editor for array / json columns
    // (doc 1206). The hidden <textarea> holds the JSON; require-form.js'
    // default `fieldlisttpl` renders the key+value rows + add/remove buttons.
    } else if (c.name === 'array' || c.name === 'json' || /json$/.test(c.name) || /array$/.test(c.name)) {
      inputs.push(wrap(
        `<dl class="fieldlist" data-name="row[${c.name}]">` +
        `<dd><a href="javascript:;" class="btn btn-sm btn-success btn-append"><i class="fa fa-plus"></i> 追加</a></dd>` +
        `<textarea name="row[${c.name}]" class="form-control hide" rows="5"></textarea>` +
        `</dl>`,
      ))
    // select (selectpicker / bootstrap-select, doc 185) — enum, set, or any
    // column whose comment carries a `key=value,key=value` option map. A
    // `(多选)` marker (or the set type) makes it a multi-select.
    } else if (c.enumValues || parseOptionComment(c.comment ?? '')) {
      const parsed = parseOptionComment(c.comment ?? '')
      const multiple = c.dataType === 'set' || (parsed?.multiple ?? false)
      const options: Array<[string, string]> = parsed
        ? parsed.options
        : (c.enumValues ?? []).map((v) => [v, v] as [string, string])
      const optsHtml = options.map(([k, v]) => `<option value="${k}">${v}</option>`).join('')
      const nm = multiple ? `row[${c.name}][]` : `row[${c.name}]`
      const mult = multiple ? ' multiple' : ''
      inputs.push(wrap(`<select class="form-control selectpicker"${mult}${ruleAttr} name="${nm}">${optsHtml}</select>`))
    // text → textarea. A `content` column additionally gets the `editor`
    // class — FastAdmin's `php think crud` editorfield default — so an
    // installed rich-text editor addon hooks it; without one it degrades to a
    // plain textarea, exactly like FastAdmin core.
    } else if (['text', 'longtext', 'mediumtext'].includes(c.dataType)) {
      const cls = c.name === 'content' ? 'form-control editor' : 'form-control'
      inputs.push(wrap(`<textarea class="${cls}"${ruleAttr} name="row[${c.name}]"></textarea>`))
    // default — number / text input.
    } else {
      const type = ['int', 'bigint', 'decimal', 'float', 'double'].includes(c.dataType) ? 'number' : 'text'
      inputs.push(wrap(`<input class="form-control" type="${type}"${ruleAttr} name="row[${c.name}]" value="">`))
    }
  }
  return inputs.join(' +\n        ') || `''`
}

function escapeForTemplate(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

/**
 * Parse a FastAdmin-style column comment into a field label + option map.
 * FastAdmin's CRUD writes comments like `状态值:0=禁用,1=正常,2=推荐` or
 * `性别(单选):male=男,female=女` — the text before the first `:` is the field
 * label, the rest is a `key=value,key=value` choice map. Returns null when the
 * comment carries no clean option map (so the column is not a <select>).
 * A `多选` marker anywhere in the comment flags a multi-select.
 */
function parseOptionComment(
  comment: string,
): { label: string; multiple: boolean; options: Array<[string, string]> } | null {
  const idx = (comment || '').indexOf(':')
  if (idx < 0) return null
  const label = comment.slice(0, idx).trim()
  const options: Array<[string, string]> = []
  for (const pair of comment.slice(idx + 1).split(',')) {
    const eq = pair.indexOf('=')
    if (eq <= 0) return null // not a clean k=v map — treat as a plain comment
    options.push([pair.slice(0, eq).trim(), pair.slice(eq + 1).trim()])
  }
  if (options.length === 0) return null
  return { label, multiple: /多选/.test(comment), options }
}
