// Auto-generated by `bin/think crud -t fa_test`. Edit freely.
import { Column, Entity, PrimaryGeneratedColumn, PrimaryColumn } from 'typeorm'

@Entity({ name: 'fa_test' })
export class TestEntity {
  @PrimaryGeneratedColumn({ type: 'int' })
  id!: number

  @Column({ type: 'int', nullable: true, default: "0", comment: "会员ID" })
  user_id!: number | null

  @Column({ type: 'int', nullable: true, default: "0", comment: "管理员ID" })
  admin_id!: number | null

  @Column({ type: 'int', unsigned: true, nullable: true, default: "0", comment: "分类ID(单选)" })
  category_id!: number | null

  @Column({ type: 'varchar', length: 100, nullable: true, comment: "分类ID(多选)" })
  category_ids!: string | null

  @Column({ type: 'varchar', length: 255, nullable: true, default: '', comment: "标签" })
  tags!: string | null

  @Column({ type: 'enum', enum: ["monday","tuesday","wednesday"], nullable: true, comment: "星期(单选):monday=星期一,tuesday=星期二,wednesday=星期三" })
  week!: string | null

  @Column({ type: 'varchar', length: 19, nullable: true, default: '', comment: "标志(多选):hot=热门,index=首页,recommend=推荐" })
  flag!: string | null

  @Column({ type: 'enum', enum: ["male","female"], nullable: true, default: "male", comment: "性别(单选):male=男,female=女" })
  genderdata!: string | null

  @Column({ type: 'varchar', length: 22, nullable: true, comment: "爱好(多选):music=音乐,reading=读书,swimming=游泳" })
  hobbydata!: string | null

  @Column({ type: 'varchar', length: 100, nullable: true, default: '', comment: "标题" })
  title!: string | null

  @Column({ type: 'text', nullable: true, comment: "内容" })
  content!: string | null

  @Column({ type: 'varchar', length: 100, nullable: true, default: '', comment: "图片" })
  image!: string | null

  @Column({ type: 'varchar', length: 1500, nullable: true, default: '', comment: "图片组" })
  images!: string | null

  @Column({ type: 'varchar', length: 100, nullable: true, default: '', comment: "附件" })
  attachfile!: string | null

  @Column({ type: 'varchar', length: 255, nullable: true, default: '', comment: "关键字" })
  keywords!: string | null

  @Column({ type: 'varchar', length: 255, nullable: true, default: '', comment: "描述" })
  description!: string | null

  @Column({ type: 'varchar', length: 100, nullable: true, default: '', comment: "省市" })
  city!: string | null

  @Column({ type: 'varchar', length: 255, nullable: true, default: '', comment: "数组:value=值" })
  array!: string | null

  @Column({ type: 'varchar', length: 255, nullable: true, default: '', comment: "配置:key=名称,value=值" })
  json!: string | null

  @Column({ type: 'varchar', length: 1500, nullable: true, default: '', comment: "二维数组:title=标题,intro=介绍,author=作者,age=年龄" })
  multiplejson!: string | null

  @Column({ type: 'decimal', unsigned: true, nullable: true, default: "0.00", comment: "价格" })
  price!: number | null

  @Column({ type: 'int', unsigned: true, nullable: true, default: "0", comment: "点击" })
  views!: number | null

  @Column({ type: 'varchar', length: 100, nullable: true, default: '', comment: "时间区间" })
  workrange!: string | null

  @Column({ type: 'date', nullable: true, comment: "开始日期" })
  startdate!: string | null

  @Column({ type: 'datetime', nullable: true, comment: "活动时间(datetime)" })
  activitytime!: string | null

  @Column({ type: 'year', nullable: true, comment: "年" })
  year!: string | null

  @Column({ type: 'time', nullable: true, comment: "时间" })
  times!: string | null

  @Column({ type: 'bigint', transformer: { from: (v: string | null) => v == null ? null : Number(v), to: (v: number | null) => v }, nullable: true, comment: "刷新时间" })
  refreshtime!: number | null

  @Column({ type: 'bigint', transformer: { from: (v: string | null) => v == null ? null : Number(v), to: (v: number | null) => v }, nullable: true, comment: "创建时间" })
  createtime!: number | null

  @Column({ type: 'bigint', transformer: { from: (v: string | null) => v == null ? null : Number(v), to: (v: number | null) => v }, nullable: true, comment: "更新时间" })
  updatetime!: number | null

  @Column({ type: 'bigint', transformer: { from: (v: string | null) => v == null ? null : Number(v), to: (v: number | null) => v }, nullable: true, comment: "删除时间" })
  deletetime!: number | null

  @Column({ type: 'int', nullable: true, default: "0", comment: "权重" })
  weigh!: number | null

  @Column({ type: 'tinyint', nullable: true, default: "0", comment: "开关" })
  switch!: boolean | null

  @Column({ type: 'enum', enum: ["normal","hidden"], nullable: true, default: "normal", comment: "状态" })
  status!: string | null

  @Column({ type: 'enum', enum: ["0","1","2"], nullable: true, default: "1", comment: "状态值:0=禁用,1=正常,2=推荐" })
  state!: string | null

}