// Auto-generated by `bin/think crud -t fa_test`. Edit freely.
import { All, Body, Controller, Get, HttpCode, Param, Post, Query, Req, UseGuards } from '@nestjs/common'
import { InjectRepository } from '@nestjs/typeorm'
import { Repository } from 'typeorm'
import type { Request } from 'express'
import { TestEntity } from '../../entities/test.entity.ts'
import { adminErr, adminOk, type AdminEnvelope } from '../../common/envelope.ts'
import { AdminAuthGuard } from '../../guards/admin-auth.guard.ts'
import { CsrfService, type SessionWithToken } from '../../services/csrf.service.ts'
import { BackendCrudService, parseStr } from '../../services/backend-crud.service.ts'
import { ViewService } from '../../services/view.service.ts'
import { NoNeedRight } from '../../common/no-need-right.decorator.ts'

interface TestSession extends SessionWithToken {
  admin?: { id: number; username: string } | undefined
}
type TestReq = Request & { session: TestSession & { [k: string]: unknown } }

@Controller('admin.php/test')
@UseGuards(AdminAuthGuard)
@NoNeedRight(['selectpage'])
export class TestController {
  private readonly crud: BackendCrudService<TestEntity>

  constructor(
    @InjectRepository(TestEntity) private readonly repo: Repository<TestEntity>,
    private readonly csrf: CsrfService,
    private readonly view: ViewService,
  ) {
    this.crud = new BackendCrudService(this.repo, {
      searchFields: 'category_ids,tags,title',
      multiFields: 'status',
    })
  }

  @Get('index')
  async indexGet(@Req() req: TestReq, @Query() q: Record<string, string>): Promise<unknown> {
    if (!isAjax(req)) {
      return this.view.renderListPage({
        pageTitle: 'Test',
        tableId: 'table',
        indexUrl: '/admin.php/test/index',
        addUrl: '/admin.php/test/add',
        editUrl: '/admin.php/test/edit',
        delUrl: '/admin.php/test/del',
        multiUrl: '/admin.php/test/multi',
        importUrl: '/admin.php/test/import',
        recyclebinUrl: '/admin.php/test/recyclebin',
        // A CRUD-generated controller has no PHP-asset backend JS file, so the
        // bootstrap-table is initialised inline; columns must be supplied.
        useInlineInit: true,
        columns: [
        { checkbox: true },
        { field: 'id', title: 'Id', sortable: true },
        { field: 'user_id', title: 'User Id' },
        { field: 'admin_id', title: 'Admin Id' },
        { field: 'category_id', title: 'Category Id' },
        { field: 'category_ids', title: 'Category Ids' },
        { field: 'tags', title: 'Tags' },
        { field: 'week', title: 'Week' },
        { field: 'flag', title: 'Flag' },
        { field: 'genderdata', title: 'Genderdata' },
        { field: 'hobbydata', title: 'Hobbydata' },
        { operate: true, title: 'Operate' },
      ],
        req,
        controllername: 'test',
        actionname: 'index',
      })
    }
    return this.crud.index(q as Record<string, unknown>)
  }

  @Post('index')
  @HttpCode(200)
  async indexPost(@Query() q: Record<string, string>): Promise<{ total: number; rows: TestEntity[] }> {
    return this.crud.index(q as Record<string, unknown>)
  }

  @Get('add')
  getAdd(@Req() req: TestReq): string {
    const tok = this.csrf.issue(req.session)
    return this.view.renderFormPage({
      pageTitle: 'Test - Add',
      formId: 'add-form',
      formAction: '/admin.php/test/add',
      __token__: tok,
      fields: '<div class="form-group"><label class="col-xs-2 control-label">会员ID</label><div class="col-xs-8"><input class="form-control selectpage" data-source="user/user/selectpage" name="row[user_id]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">管理员ID</label><div class="col-xs-8"><input class="form-control selectpage" data-source="auth/admin/selectpage" name="row[admin_id]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">分类ID(单选)</label><div class="col-xs-8"><input class="form-control selectpage" data-source="category/selectpage" name="row[category_id]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">分类ID(多选)</label><div class="col-xs-8"><input class="form-control selectpage" data-source="category/selectpage" data-multiple="true" name="row[category_ids]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">标签</label><div class="col-xs-8"><input class="form-control" data-role="tagsinput" name="row[tags]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">星期(单选):monday=星期一,tuesday=星期二,wednesday=星期三</label><div class="col-xs-8"><select class="form-control selectpicker" name="row[week]"><option value="monday">星期一</option><option value="tuesday">星期二</option><option value="wednesday">星期三</option></select></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">标志(多选):hot=热门,index=首页,recommend=推荐</label><div class="col-xs-8"><select class="form-control selectpicker" multiple name="row[flag][]"><option value="hot">热门</option><option value="index">首页</option><option value="recommend">推荐</option></select></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">性别(单选):male=男,female=女</label><div class="col-xs-8"><select class="form-control selectpicker" name="row[genderdata]"><option value="male">男</option><option value="female">女</option></select></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">爱好(多选):music=音乐,reading=读书,swimming=游泳</label><div class="col-xs-8"><select class="form-control selectpicker" multiple name="row[hobbydata][]"><option value="music">音乐</option><option value="reading">读书</option><option value="swimming">游泳</option></select></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">标题</label><div class="col-xs-8"><input class="form-control" type="text" name="row[title]" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">内容</label><div class="col-xs-8"><textarea class="form-control editor" name="row[content]"></textarea></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">图片</label><div class="col-xs-8"><div class="input-group"><input id="c-image" class="form-control" name="row[image]" type="text" value=""><div class="input-group-addon no-border no-padding"><span><button type="button" class="btn btn-danger faupload" data-input-id="c-image" data-mimetype="image/*" data-multiple="false"><i class="fa fa-upload"></i> 上传</button></span> <span><button type="button" class="btn btn-primary fachoose" data-input-id="c-image" data-mimetype="image/*" data-multiple="false"><i class="fa fa-list"></i> 选择</button></span></div></div></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">图片组</label><div class="col-xs-8"><div class="input-group"><input id="c-images" class="form-control" name="row[images]" type="text" value=""><div class="input-group-addon no-border no-padding"><span><button type="button" class="btn btn-danger faupload" data-input-id="c-images" data-mimetype="image/*" data-multiple="true"><i class="fa fa-upload"></i> 上传</button></span> <span><button type="button" class="btn btn-primary fachoose" data-input-id="c-images" data-mimetype="image/*" data-multiple="true"><i class="fa fa-list"></i> 选择</button></span></div></div></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">附件</label><div class="col-xs-8"><div class="input-group"><input id="c-attachfile" class="form-control" name="row[attachfile]" type="text" value=""><div class="input-group-addon no-border no-padding"><span><button type="button" class="btn btn-danger faupload" data-input-id="c-attachfile" data-mimetype="*" data-multiple="false"><i class="fa fa-upload"></i> 上传</button></span> <span><button type="button" class="btn btn-primary fachoose" data-input-id="c-attachfile" data-mimetype="*" data-multiple="false"><i class="fa fa-list"></i> 选择</button></span></div></div></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">关键字</label><div class="col-xs-8"><input class="form-control" type="text" name="row[keywords]" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">描述</label><div class="col-xs-8"><input class="form-control" type="text" name="row[description]" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">省市</label><div class="col-xs-8"><input class="form-control" data-toggle="city-picker" name="row[city]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">数组:value=值</label><div class="col-xs-8"><dl class="fieldlist" data-name="row[array]"><dd><a href="javascript:;" class="btn btn-sm btn-success btn-append"><i class="fa fa-plus"></i> 追加</a></dd><textarea name="row[array]" class="form-control hide" rows="5"></textarea></dl></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">配置:key=名称,value=值</label><div class="col-xs-8"><dl class="fieldlist" data-name="row[json]"><dd><a href="javascript:;" class="btn btn-sm btn-success btn-append"><i class="fa fa-plus"></i> 追加</a></dd><textarea name="row[json]" class="form-control hide" rows="5"></textarea></dl></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">二维数组:title=标题,intro=介绍,author=作者,age=年龄</label><div class="col-xs-8"><dl class="fieldlist" data-name="row[multiplejson]"><dd><a href="javascript:;" class="btn btn-sm btn-success btn-append"><i class="fa fa-plus"></i> 追加</a></dd><textarea name="row[multiplejson]" class="form-control hide" rows="5"></textarea></dl></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">价格</label><div class="col-xs-8"><input class="form-control" type="number" name="row[price]" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">点击</label><div class="col-xs-8"><input class="form-control" type="number" name="row[views]" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">时间区间</label><div class="col-xs-8"><input class="form-control datetimerange" name="row[workrange]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">开始日期</label><div class="col-xs-8"><input class="form-control datetimepicker" data-date-format="YYYY-MM-DD" name="row[startdate]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">活动时间(datetime)</label><div class="col-xs-8"><input class="form-control datetimepicker" data-date-format="YYYY-MM-DD HH:mm:ss" name="row[activitytime]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">年</label><div class="col-xs-8"><input class="form-control" type="text" name="row[year]" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">时间</label><div class="col-xs-8"><input class="form-control" type="text" name="row[times]" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">刷新时间</label><div class="col-xs-8"><input class="form-control datetimepicker" data-date-format="YYYY-MM-DD HH:mm:ss" name="row[refreshtime]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">权重</label><div class="col-xs-8"><input class="form-control" type="number" name="row[weigh]" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">开关</label><div class="col-xs-8"><input id="c-switch" name="row[switch]" type="hidden" value="1"><a href="javascript:;" data-toggle="switcher" class="btn-switcher" data-input-id="c-switch" data-yes="1" data-no="0"><i class="fa fa-toggle-on text-success fa-2x"></i></a></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">状态</label><div class="col-xs-8"><select class="form-control selectpicker" name="row[status]"><option value="normal">normal</option><option value="hidden">hidden</option></select></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">状态值:0=禁用,1=正常,2=推荐</label><div class="col-xs-8"><select class="form-control selectpicker" name="row[state]"><option value="0">禁用</option><option value="1">正常</option><option value="2">推荐</option></select></div></div>',
      req,
      controllername: 'test',
      actionname: 'add',
    })
  }

  @Post('add')
  @HttpCode(200)
  async postAdd(@Req() req: TestReq, @Body() body: Record<string, unknown>): Promise<AdminEnvelope<unknown>> {
    if (!this.csrf.consume(req.session, String(body['__token__'] ?? ''))) {
      return adminErr('Token verification error', { __token__: this.csrf.issue(req.session) })
    }
    const row = body['row']
    if (!row || typeof row !== 'object') return adminErr('Parameter %s can not be empty')
    const r = await this.crud.add(row as Record<string, unknown>)
    if (!r.ok) return adminErr(r.error ?? 'No rows were inserted')
    return adminOk('', { id: r.id })
  }

  @Get('edit/ids/:id')
  async getEdit(@Req() req: TestReq, @Param('id') idStr: string): Promise<unknown> {
    const id = parseInt(idStr, 10)
    const row = await this.repo.findOneBy({ id } as any)
    if (!row) return adminErr('No Results were found')
    const tok = this.csrf.issue(req.session)
    return this.view.renderFormPage({
      pageTitle: 'Test - Edit',
      formId: 'edit-form',
      formAction: '/admin.php/test/edit',
      __token__: tok,
      idsField: `<input type="hidden" name="ids" value="${id}">`,
      fields: '<div class="form-group"><label class="col-xs-2 control-label">会员ID</label><div class="col-xs-8"><input class="form-control selectpage" data-source="user/user/selectpage" name="row[user_id]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">管理员ID</label><div class="col-xs-8"><input class="form-control selectpage" data-source="auth/admin/selectpage" name="row[admin_id]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">分类ID(单选)</label><div class="col-xs-8"><input class="form-control selectpage" data-source="category/selectpage" name="row[category_id]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">分类ID(多选)</label><div class="col-xs-8"><input class="form-control selectpage" data-source="category/selectpage" data-multiple="true" name="row[category_ids]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">标签</label><div class="col-xs-8"><input class="form-control" data-role="tagsinput" name="row[tags]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">星期(单选):monday=星期一,tuesday=星期二,wednesday=星期三</label><div class="col-xs-8"><select class="form-control selectpicker" name="row[week]"><option value="monday">星期一</option><option value="tuesday">星期二</option><option value="wednesday">星期三</option></select></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">标志(多选):hot=热门,index=首页,recommend=推荐</label><div class="col-xs-8"><select class="form-control selectpicker" multiple name="row[flag][]"><option value="hot">热门</option><option value="index">首页</option><option value="recommend">推荐</option></select></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">性别(单选):male=男,female=女</label><div class="col-xs-8"><select class="form-control selectpicker" name="row[genderdata]"><option value="male">男</option><option value="female">女</option></select></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">爱好(多选):music=音乐,reading=读书,swimming=游泳</label><div class="col-xs-8"><select class="form-control selectpicker" multiple name="row[hobbydata][]"><option value="music">音乐</option><option value="reading">读书</option><option value="swimming">游泳</option></select></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">标题</label><div class="col-xs-8"><input class="form-control" type="text" name="row[title]" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">内容</label><div class="col-xs-8"><textarea class="form-control editor" name="row[content]"></textarea></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">图片</label><div class="col-xs-8"><div class="input-group"><input id="c-image" class="form-control" name="row[image]" type="text" value=""><div class="input-group-addon no-border no-padding"><span><button type="button" class="btn btn-danger faupload" data-input-id="c-image" data-mimetype="image/*" data-multiple="false"><i class="fa fa-upload"></i> 上传</button></span> <span><button type="button" class="btn btn-primary fachoose" data-input-id="c-image" data-mimetype="image/*" data-multiple="false"><i class="fa fa-list"></i> 选择</button></span></div></div></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">图片组</label><div class="col-xs-8"><div class="input-group"><input id="c-images" class="form-control" name="row[images]" type="text" value=""><div class="input-group-addon no-border no-padding"><span><button type="button" class="btn btn-danger faupload" data-input-id="c-images" data-mimetype="image/*" data-multiple="true"><i class="fa fa-upload"></i> 上传</button></span> <span><button type="button" class="btn btn-primary fachoose" data-input-id="c-images" data-mimetype="image/*" data-multiple="true"><i class="fa fa-list"></i> 选择</button></span></div></div></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">附件</label><div class="col-xs-8"><div class="input-group"><input id="c-attachfile" class="form-control" name="row[attachfile]" type="text" value=""><div class="input-group-addon no-border no-padding"><span><button type="button" class="btn btn-danger faupload" data-input-id="c-attachfile" data-mimetype="*" data-multiple="false"><i class="fa fa-upload"></i> 上传</button></span> <span><button type="button" class="btn btn-primary fachoose" data-input-id="c-attachfile" data-mimetype="*" data-multiple="false"><i class="fa fa-list"></i> 选择</button></span></div></div></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">关键字</label><div class="col-xs-8"><input class="form-control" type="text" name="row[keywords]" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">描述</label><div class="col-xs-8"><input class="form-control" type="text" name="row[description]" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">省市</label><div class="col-xs-8"><input class="form-control" data-toggle="city-picker" name="row[city]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">数组:value=值</label><div class="col-xs-8"><dl class="fieldlist" data-name="row[array]"><dd><a href="javascript:;" class="btn btn-sm btn-success btn-append"><i class="fa fa-plus"></i> 追加</a></dd><textarea name="row[array]" class="form-control hide" rows="5"></textarea></dl></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">配置:key=名称,value=值</label><div class="col-xs-8"><dl class="fieldlist" data-name="row[json]"><dd><a href="javascript:;" class="btn btn-sm btn-success btn-append"><i class="fa fa-plus"></i> 追加</a></dd><textarea name="row[json]" class="form-control hide" rows="5"></textarea></dl></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">二维数组:title=标题,intro=介绍,author=作者,age=年龄</label><div class="col-xs-8"><dl class="fieldlist" data-name="row[multiplejson]"><dd><a href="javascript:;" class="btn btn-sm btn-success btn-append"><i class="fa fa-plus"></i> 追加</a></dd><textarea name="row[multiplejson]" class="form-control hide" rows="5"></textarea></dl></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">价格</label><div class="col-xs-8"><input class="form-control" type="number" name="row[price]" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">点击</label><div class="col-xs-8"><input class="form-control" type="number" name="row[views]" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">时间区间</label><div class="col-xs-8"><input class="form-control datetimerange" name="row[workrange]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">开始日期</label><div class="col-xs-8"><input class="form-control datetimepicker" data-date-format="YYYY-MM-DD" name="row[startdate]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">活动时间(datetime)</label><div class="col-xs-8"><input class="form-control datetimepicker" data-date-format="YYYY-MM-DD HH:mm:ss" name="row[activitytime]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">年</label><div class="col-xs-8"><input class="form-control" type="text" name="row[year]" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">时间</label><div class="col-xs-8"><input class="form-control" type="text" name="row[times]" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">刷新时间</label><div class="col-xs-8"><input class="form-control datetimepicker" data-date-format="YYYY-MM-DD HH:mm:ss" name="row[refreshtime]" type="text" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">权重</label><div class="col-xs-8"><input class="form-control" type="number" name="row[weigh]" value=""></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">开关</label><div class="col-xs-8"><input id="c-switch" name="row[switch]" type="hidden" value="1"><a href="javascript:;" data-toggle="switcher" class="btn-switcher" data-input-id="c-switch" data-yes="1" data-no="0"><i class="fa fa-toggle-on text-success fa-2x"></i></a></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">状态</label><div class="col-xs-8"><select class="form-control selectpicker" name="row[status]"><option value="normal">normal</option><option value="hidden">hidden</option></select></div></div>' +
        '<div class="form-group"><label class="col-xs-2 control-label">状态值:0=禁用,1=正常,2=推荐</label><div class="col-xs-8"><select class="form-control selectpicker" name="row[state]"><option value="0">禁用</option><option value="1">正常</option><option value="2">推荐</option></select></div></div>',
      req,
      controllername: 'test',
      actionname: 'edit',
    })
  }

  @Post('edit')
  @HttpCode(200)
  async postEdit(@Req() req: TestReq, @Body() body: Record<string, unknown>): Promise<AdminEnvelope<unknown>> {
    if (!this.csrf.consume(req.session, String(body['__token__'] ?? ''))) {
      return adminErr('Token verification error', { __token__: this.csrf.issue(req.session) })
    }
    const id = parseInt(String(body['ids'] ?? '0'), 10)
    if (!Number.isFinite(id) || id <= 0) return adminErr('No Results were found')
    const row = body['row']
    if (!row || typeof row !== 'object') return adminErr('Parameter %s can not be empty')
    const r = await this.crud.edit(id, row as Record<string, unknown>)
    if (!r.ok) return adminErr(r.error ?? 'No rows were updated')
    return adminOk('')
  }

  @Post('del')
  @HttpCode(200)
  async del(@Body() body: Record<string, unknown>): Promise<AdminEnvelope<unknown>> {
    const ids = String(body['ids'] ?? '').trim()
    if (!ids) return adminErr('Parameter %s can not be empty')
    const count = await this.crud.del(ids)
    if (!count) return adminErr('No rows were deleted')
    return adminOk('')
  }

  @Post('multi')
  @HttpCode(200)
  async multi(@Body() body: Record<string, unknown>): Promise<AdminEnvelope<unknown>> {
    const ids = String(body['ids'] ?? '').trim()
    if (!ids) return adminErr('Parameter %s can not be empty')
    const paramsStr = String(body['params'] ?? '')
    if (!paramsStr) return adminErr('No rows were updated')
    const values = parseStr(paramsStr)
    const count = await this.crud.multi(ids, values, true)
    if (!count) return adminErr('No rows were updated')
    return adminOk('')
  }

  // CSV import — `.btn-import` uploads a .csv then POSTs {file: <url>} here.
  // The first CSV row is a header line matched against column comments/names.
  @Post('import')
  @HttpCode(200)
  async importRows(@Body() body: Record<string, unknown>): Promise<AdminEnvelope<unknown>> {
    const file = String(body?.['file'] ?? '').trim()
    if (!file) return adminErr('Parameter %s can not be empty')
    const r = await this.crud.import(file)
    if (!r.ok) return adminErr(r.error ?? 'No rows were updated')
    return adminOk('')
  }

  // The fastadmin-selectpage plugin POSTs its queries (doc 178); accept both.
  @All('selectpage')
  selectpage(@Query() q: Record<string, unknown>, @Body() body: Record<string, unknown>): Promise<{ list: Array<Record<string, unknown>>; total: number }> {
    return this.crud.selectpage({ ...(body ?? {}), ...q } as any)
  }

  // -------- Recycle Bin (SoftDelete trait parity) --------
  // del() above only sets `deletetime`; these actions list / restore / purge
  // the binned rows. Mirrors PHP Backend::recyclebin()/restore()/destroy().
  @Get('recyclebin')
  async recyclebinGet(@Req() req: TestReq, @Query() q: Record<string, string>): Promise<unknown> {
    if (!isAjax(req)) {
      return this.view.renderRecyclebinPage({
        pageTitle: 'Test - Recycle Bin',
        tableId: 'table',
        recyclebinUrl: '/admin.php/test/recyclebin',
        restoreUrl: '/admin.php/test/restore',
        destroyUrl: '/admin.php/test/destroy',
        columns: [
        { checkbox: true },
        { field: 'id', title: 'Id', sortable: true },
        { field: 'user_id', title: 'User Id' },
        { field: 'admin_id', title: 'Admin Id' },
        { field: 'category_id', title: 'Category Id' },
        { field: 'category_ids', title: 'Category Ids' },
        { field: 'tags', title: 'Tags' },
        { field: 'deletetime', title: 'Delete Time', formatter: 'Table.api.formatter.datetime' },
        { operate: true, title: 'Operate' },
      ],
        req,
        controllername: 'test',
        actionname: 'recyclebin',
      })
    }
    return this.crud.recyclebin(q as Record<string, unknown>)
  }

  @Post('recyclebin')
  @HttpCode(200)
  async recyclebinPost(@Query() q: Record<string, string>): Promise<{ total: number; rows: TestEntity[] }> {
    return this.crud.recyclebin(q as Record<string, unknown>)
  }

  // Empty `ids` restores / destroys the whole bin — that's what the
  // `.btn-restoreall` / `.btn-destroyall` toolbar buttons POST (no ids).
  @Post('restore')
  @HttpCode(200)
  async restore(@Body() body: Record<string, unknown>, @Query() q: Record<string, string>): Promise<AdminEnvelope<unknown>> {
    // `@Body()` is `undefined` for a POST with no body — that is exactly what
    // the no-id `.btn-restoreall` / `.btn-destroyall` toolbar buttons send, so
    // both accessors must be optional-chained.
    const ids = String(body?.['ids'] ?? q?.['ids'] ?? '').trim()
    const count = await this.crud.restore(ids)
    if (!count) return adminErr('No rows were updated')
    return adminOk('')
  }

  @Post('destroy')
  @HttpCode(200)
  async destroy(@Body() body: Record<string, unknown>, @Query() q: Record<string, string>): Promise<AdminEnvelope<unknown>> {
    // `@Body()` is `undefined` for a POST with no body — that is exactly what
    // the no-id `.btn-restoreall` / `.btn-destroyall` toolbar buttons send, so
    // both accessors must be optional-chained.
    const ids = String(body?.['ids'] ?? q?.['ids'] ?? '').trim()
    const count = await this.crud.destroy(ids)
    if (!count) return adminErr('No rows were updated')
    return adminOk('')
  }
}

function isAjax(req: Request): boolean {
  return String(req.headers['x-requested-with'] ?? '').toLowerCase() === 'xmlhttprequest'
}
